### ISSUE TITLE
UE4_Minimap for multiplayer

### ISSUE THREAD

**Issue by raghul1129** [damirporobic/UE4_Minimap#1]
i want t o use this minimap for a multiplayer game ,how to attach this widget ?in my project file?

**Comment by DamirPorobic** [comment]
Have you checked the "Getting Started"  section of the wiki pages?  https://github.com/damirporobic/UE4_Minimap/wiki/1.-Getting-Started

Basically you should download this projects, copy the files explained in the wiki file to your project,  then create a new widget in your project and add it to the viewport. 

Have a look at the wiki page and let me know if you have any questions.

**Comment by raghul1129** [comment]
i mean ,how to add actor widgets dynamically ,you did it on the beginplay ,i want to add whenever a player is joined the game?

**Comment by DamirPorobic** [comment]
You are talking about adding POIs dynamically or adding the map widget?  Every of your players should have its own minimap widget and POIs are added based on the tag, so there is nothing to do except setting the tag under the minimap widget and the same tag under the acot that you want to show. Where do you add the widget is not important,  i have added it under begin play just as an example.

**Comment by raghul1129** [comment]
Thanks for the reply,now its working :)

**Comment by DamirPorobic** [comment]
Great to hear that.  :)
