### ISSUE TITLE
Multiplayer player client location error

### ISSUE THREAD

**Issue by raghul1129** [damirporobic/UE4_Minimap#3]
i have implimented your project in my project,minimap is working fine in server but in the clients the location of other  players is getting attached to the current player how to fix this?[https://www.dropbox.com/s/uih8zm3rg3fnuu6/Location_error.webm?dl=0](url)

**Comment by DamirPorobic** [comment]
What I can see from the shared video is that the character is moving away from other actor, that seems to be correct, but the map is also moving, this seems to be related to incorrect set map properties. Can you please share:
- Image that you use as background
- Top view screenshot of your UE Map, can be taken in the editor 
- Screenshot of map properties that you have set.

**Comment by raghul1129** [comment]
Minimap locations are perfect ,the location of each actor is shown correctly on server ,only clients has that error

**Comment by DamirPorobic** [comment]
As said, please share:
- Image that you use as background
- Top view screenshot of your UE Map, can be taken in the editor
- Screenshot of map properties that you have set.

**Comment by Rko619** [comment]
[https://www.dropbox.com/s/y498ceyy4ig15dz/Texture.PNG?dl=0](url)
[https://www.dropbox.com/s/848x7fj6nce3lcf/Props.PNG?dl=0](url)

**Comment by raghul1129** [comment]
![props](https://cloud.githubusercontent.com/assets/20899479/18912493/443eeee4-85a0-11e6-9499-54bc1313fa6a.PNG)
![texture](https://cloud.githubusercontent.com/assets/20899479/18912494/4442a764-85a0-11e6-9761-de2e90337fe7.PNG)

**Comment by DamirPorobic** [comment]
Can you also post your original map texture?

**Comment by raghul1129** [comment]
![texture2](https://cloud.githubusercontent.com/assets/20899479/18913116/ac833f8e-85a3-11e6-9115-c41df58d9fa5.png)

**Comment by DamirPorobic** [comment]
Ok, and this is the length of your UE4 map?
![capture](https://cloud.githubusercontent.com/assets/12796236/18913523/90ca320e-8588-11e6-95a2-7523470bdf08.PNG)

**Comment by raghul1129** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/20899479/18927311/05e582fa-85d9-11e6-8b4e-e04c3a236b9d.png)
 i took that value as in the image.

**Comment by DamirPorobic** [comment]
Well yeah, that should be the same. So, question now, is there anything different between your server and client? The widget takes always the current player location and uses those values that you have provided to calculate the map movement. There must be something different between the client and server.

I've just run the sample mini map projects with two clients and the map was working fine on both, which is something I would expect, every minimap is a widget of it's own and has nothing to do with other minimap widget.

Can you try to run the example project with two clients and see how it behaves?

**Comment by raghul1129** [comment]
i have tried it already it works fine with your project, for my my project its like that

**Comment by raghul1129** [comment]
one thing i have changed in your code, you have made to set the static poi on begin play of ThirdPerson character , i changed the static class to Thirdperson class so that it can detect players,then instead of adding players in beginplay of Thirdperson character i have added them in event tick in minimap widget so that every player joins can be visible in map,is the logic ok or i have to modify?

**Comment by DamirPorobic** [comment]
For detecting other players you should use tags. Like explained here https://github.com/damirporobic/UE4_Minimap/wiki/1.-Getting-Started#implementing-the-widget

Basically what it does when a new player joins, and he hits the collision sphere he is added to the map. In this way you can give different color to enemies or NPC, what ever fits your need.

**Comment by raghul1129** [comment]
i need to do without the collision sphere, i am doing an FPS game for that will this work?

**Comment by DamirPorobic** [comment]
Why would it not? The sphere is not blocking, you just check for overlap. Don't see a problem there

**Comment by raghul1129** [comment]
if i use always collide condition will that be working fine?

**Comment by DamirPorobic** [comment]
You can use more then one collision sphere on you character, for example one for map that those only overlap and another that checks for projectile hits.

**Comment by raghul1129** [comment]
youre not talking about that ue4 thing in the map,did you?youre telling that i dont have to change any thing except the widget values rite?if not what should i change and one more thing how to make the texture rotate as the player turns like Call of Duty?

**Comment by Rko619** [comment]
its working now thanks ,its due to the sphere after adding it works,and how to rotate the texture do you have any idea on that?

**Comment by raghul1129** [comment]
its working now thanks ,its due to the sphere after adding it works,and how to rotate the texture do you have any idea on that?

**Comment by DamirPorobic** [comment]
Great to hear that it works. The map rotation is currently not implemented, eventually one day in future but for now you would need to look into that by yourself. The problem with the map rotation is that you need to add the logic everywhere which is not impossible but requires some work.
